appc/spec

schema/types/dependencies.go, schema/types/dependencies_test.go
As in #37 Dependency.ImageID is optional.
Unmarshalling a json or programmaticaly creating an ImageManifest without a dependency's ImageID will create an empty ImageId Hash struct. On Marshall it will call assertValid that will correctly fail.
This patch makes ImageID a pointer. I made a different fix here: 23b834b2a3da76b5797c3c92a3a198f875dfb0c3. This is the rationale:
The typical and fast solution is to make ImageID a pointer so on Marshall it won't call assertValid as it's a null object (see ).
The downside is that every Dependency struct's user should verify that ImageID isn't nil before doing any operation. Plus Hash has already an IsEmpty function, so there're can be nil ImageID or an empty ImageID creating some confusion.
There's a need for go json to not Marshal "zero"/empty …
=> schema: Fix optional Dependency.ImageID

SPEC.md, examples/image.json
This is one of the common isolator missing from the spec.
I have used the same format as the cgroup interface.
Signed-off-by: Rohit Jnagal <jnagal@google.com>
=> spec: Add cpu mask to isolators.

examples/image.json
Adds a missing space between two capabilities.
Signed-off-by: Rohit Jnagal jnagal@google.com
=> examples: Fix capabilities format in spec.

SPEC.md, examples/image.json
The example image manifest in the spec and in examples/image.json contain a
dependency's "root" that was removed from the spec.
=> spec: remove dependency's "root"

SPEC.md
isolators was previously changed to be a list of structs rather than a struct
itself but unfortunately it seems like the actual example embedded in the
SPEC.md was not properly updated (on the other hand, the example JSON is
fine).
h/t @cdaylward
=> spec: change isolators example to list

discovery/http.go, discovery/http_test.go
Symptoms:
$ sudo ./bin/rkt run foo
panic: runtime error: invalid memory address or nil pointer dereference
Fixed by checking if res is nil.
Additionally, only release res.Body with closeBody(res) if the http method is
attempted. Otherwise, it would be released a second time at the end of the
function.
=> discovery: httpsOrHTTP: fix error management

.travis.yml, README.md
We have had too many commits slip in that break the build/tests.
=> *: add travis

ace/validator.go
4b128a485bc00687dc8d6f3bcb1adbe6e2c255dd tried to standardise on stderr() but
unfortunately updated the validator to use the function when it's in a
different package; this wasn't caught since we did not have travis confiugred.
For now just introduce the same function to this package.
=> acevalidator: fix stderr reference

discovery/discovery.go, discovery/discovery_test.go, discovery/parse.go
This is related to #60 and #73. If my thought are wrong please let me know.
If correct probably this should be explained in the spec and maybe also #4 and maybe the app parsing functions should be moved in a new lib outside discovery?
The app and labels serialization format parsed by NewAppFromString is not
strictly related to discovery/fetching but should also be used by other
functions (eg. asking an image to a local store without discovery and fetching).
Setting a default version label if it's missing shouldn't be done here but from
the functions that needs it (now in doDiscover).
=> discovery: set default version label in doDiscover and not in NewAppFromString

README.md, SPEC.md, ace/image_manifest_main.json, ace/image_manifest_sidekick.json, examples/container.json, examples/image.json, schema/types/annotations.go, schema/types/isolator.go, schema/types/labels.go, schema/types/labels_test.go
Update README, SPEC, types, and example manifests.
=> schema: Change 'val' abbreviation to 'value' for all name/value pairs.

aci/file.go, aci/file_test.go, test
Currently there is no easy way to work with ACI images. Implementations
of the App Container Spec must understand low level details of the ACI
package format in order to complete simple tasks such as extracting
metadata and detecting the type of compression being used.
The ACI package now includes three helper functions for working with ACI
images: ManifestFromImage, NewCompressedTarReader, and NewCompressedReader.
=> aci: add helper functions for working with ACI images

SPEC.md
Currently the spec does not provided any details regarding the behavior
an implementation should exhibit when an HTTP redirect is encountered
during the image discovery process.
Add clarity by suggesting that HTTP redirects should be followed if
discovery URL returns a 3xx status code.
Fixes #97
=> spec: describe behavior of HTTP redirection during image discovery

SPEC.md
Separately call out signature validation, and add an example. Other minor
tweaks to wording for clarification.
=> spec: clarify discovery validation/authentication

schema/types/annotations.go, schema/types/annotations_test.go
Set was acting on an Annotations value instead of a pointer, which is never 
going to work for obvious reasons. This changes the receiver to a pointer and
corrects the logic to properly set the value in-place if necessary.
Also adds a test case for Annotations.Set which should have been there all
along and catches this issue.
Thanks to @mpasternacki for catching this silliness.
=> types: fix annotations Set method

actool/discover.go, discovery/discovery.go, discovery/discovery_test.go
This patch, should be merged together with the rocket part (coreos/rocket#398).
As the aci urls is tied with its signature url, to avoid confusion, tie them
together in their own struct.
=> discovery: Tie together ACI and Sig URLs.

SPEC.md
Made the follow modifications to the spec based on my extrapolation of what the **volumes** fields meant.
- Clarify what should occur based on kind.
- Add missing definition for source.
- Add missing definition for readOnly.
=> schema: Clarify kind, source, and readOnly for image manifest volumes.

README.md, SPEC.md, ace/image_manifest_main.json, examples/image.json, schema/types/app.go, schema/types/app_test.go, schema/types/environment.go, schema/types/environment_test.go
Make environment consistent with isolators and annotations (schema on "left", user values on "right", etc).
- Add EnvironmentVariable type.
- Add Environment alias for list of EnvironmentVariables
- Replace App.Environment field with new Environment type
- Plumb App.assertValid through to Environment.assertValid()
- Call out and test for IEEE Std 1003.1-2001 in environment variable
identifiers.
=> schema: Modify App Environment to be a list of name/value objects.

aci/writer.go, actool/build.go
At some point in the past, AddFile relied on the path to be explicitly passed
in, but now it simply uses the path that is set on the tar header it is
passed, so we can remove the argument now.
=> aci/actool: remove superfluous AddFile argument

SPEC.md, ace/image_manifest_main.json, examples/image.json
Having private-network as an optional isolator is problematic:
1. No private-network makes identity for metadata svc very difficult
2. The network is shared between all apps, reconciling conflicting
isolator values in manifests is impossible.
=> spec: remove private-network isolator

SPEC.md, ace/validator.go
- Use HMAC-512 to be consistent with the rest of the spec.
- Have verify take in object that was signed so signature doesn't
have to store it (or its digest).
=> spec: sign/verify: use hmac-512 and separate content from sig

SPEC.md, examples/image.json
I thought that exec could contain several executables to run. But the
array is just here to contain parameters. Adding parameters in the
example will make it more obvious that "exec" can only contain *one*
executable with potential parameters.
=> spec: exec: add parameter examples

SPEC.md
https://github.com/appc/spec/blob/master/SPEC.md#metadata-server list examples for URL endpoints like "Retrievable at http://$AC_METADATA_URL/acMetadata/v1/container". The default for "AC_METADATA_URL" is listed as "http://169.254.169.255" (already includes a scheme).
This is at least confusing, but probably just wrong.
=> SPEC: Redundant "http" scheme in metadata URLs

aci/build.go, actool/build.go
This facilitates spec vendoring and also things like jonboulle/goaci reusing this code.
=> actool: split out BuildWalker into aci package

actool/discover.go, discovery/discovery.go, discovery/discovery_test.go
Add two new functions to let a user control the Discover walking process and
then also add attempts list to keep track of errors that were encountered along
the way.
Fixes #166
=> discovery: fix walk for keys and add debugging

SPEC.md
Since the metadata service address is specified in
AC_METADATA_URL env var, there's little value in
setting expectation that the service will be on a
particular IP. From the impl point of view, it may
be much easier to not have it listen on a particular
link-local address.
=> spec: remove mention of metadata svc on 169.254.169.255

schema/container.go, schema/container_test.go, schema/image.go, schema/image_test.go, schema/types/app.go, schema/types/errors.go, schema/version.go
These changes make it easier to programmatically construct and modify manifests.
Would it be a good idea to take that further and allow "delta JSON" for slice types (Annotations, Labels, etc): JSON unmarshaled on top of existing slice would then:
- add new element if it doesn't exist
- update existing element if there is one
- delete existing element on some marker (nil value? empty string value? special attribute that wouldn't make it into final manifest?)
=> schema: don't discard existing data when unmarshaling complex structures

actool/discover.go
If the user isn't explicit add these labels as helpers.
This fixes for example:
```
./bin/actool discover quay.io/philips/golang-isoutyet
discover walk: prefix: quay.io/philips/golang-isoutyet error: expected a 200 OK got 404
discover walk: prefix: quay.io/philips error: expected a 200 OK got 404
ACI: https://quay.io/c1/aci/quay.io/philips/golang-isoutyet/latest/aci/darwin/amd64/, Sig: https://quay.io/c1/aci/quay.io/philips/golang-isoutyet/latest/sig/darwin/amd64/
Keys: https://quay.io/aci-signing-key
```
=> actool: default os and arch to GOOS and GOARCH

README.md, SPEC.md, ace/build_aci, actool/discover.go, discovery/discovery.go, discovery/discovery_test.go
Use the .aci.asc file extension since we are expecting an ASCII armored
extension of the aci file.
Discussed on: https://github.com/appc/spec/pull/156
=> SPEC: move to .aci.asc file extension

README.md
We have moved from coreos/rocket repository so app-container directory doesn't exist anymore.
=> README: correct path to build_aci script

SPEC.md, aci/layout.go
- The image archive must not have duplicate entries (possible with tar)
- The image archive must not have extraneous top-level pathnames. Only
manifest and rootfs are valid.
Relates to issue #146. Too much? Too little?
=> schema: Restrict duplicate/extraneous files in ACI tar layout.

MAINTAINERS
This formally codifies the existing two maintainers and adds @cdaylward as a
new maintainer of the specification.
/cc @philips
=> *: add MAINTAINERS file

pkg/tarheader/pop_posix.go, pkg/tarheader/pop_posix_test.go
on posix system's, include the minor and major device number, and use the sysmacros
/cc @jonboulle @alban
=> tarheader: use minor and major macros

pkg/tarheader/pop_posix.go
On my fedora 21 system I have this warning:
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
feature_test_macros(7) says that, starting from glibc 2.20, _BSD_SOURCE is
deprecated and to use _DEFAULT_SOURCE instead.
It also suggests (to compile without warnings code that needs _BSD_SOURCE for
glibc <= 2.19) to define both _BSD_SOURCE and _DEFAULT_SOURCE.
=> tarheader: pop_posix: define also _DEFAULT_SOURCE

aci/file.go, aci/file_test.go
The tar Header.Name (for example with gnu tar) can start with ./ (for example
./manifest). In this case ManifestFromImage will fail.
Plus, I noticed that the error was strange: unexpected error EOF. This is due
to the io.EOF error not being handled. So I rewrote the code to handle it (now
it's similar to github.com/coreos/rocket/pkg/tar.ExtractTar).
=> aci: fix ManifestFromImage to handle ./manifest

GUIDE.md
Many of the details in the app container spec are carefully designed to facilitate optimisations and advanced use cases. However, this is not always immediately obvious from reading the text of the spec. Right now we just give it a passing mention in one section:
> ...implementations could increase performance and de-duplicate data by building on top of overlay filesystems, copy-on-write block devices, or a content-addressed file store. These details are orthogonal to the runtime environment.
Similarly, there are some areas (for example, metrics) which are explicitly not covered by the spec but would benefit greatly from general guidance on how implementations might address them.
We should have a document (or documents) describing suggested guidelines and best practices for …
=> add "guidelines/best practices" for implementations

SPEC.md, schema/types/acname.go, schema/types/acname_test.go
- Include constraint from RFC1123/RFC952 that the name
must begin and end with an alphanumeric character.
(not a hyphen, period, or slash)
(Opened as a point of discussion. If this seems appropriate, I can add to tests, etc)
=> schema: Clarify legal edge characters in AC Name Type

SPEC.md
Signing should happen after compression so the user is not decompressing
things that it may not trust.
Fixes #19 and #201
We decided to fix this via
https://github.com/appc/spec/pull/156/files#r23838943 but it never made
it into code.
=> SPEC: clarify that compression/encryption should happen before signing

pkg/acirenderer/acirenderer.go, pkg/acirenderer/acirenderer_test.go, pkg/acirenderer/store_test.go, test
As discussed in coreos/rocket#464 I'm opening a PR here.
This library renders an aci given a well defined list of dependencies.
A future patch will also provide the dependency resolving logic.
It adds two interfaces: ACIProvider and ACIRegistry.
The first interface is the one used by this patch and the cas has been changed
to satisfy it.
The second interface will be used by the dependency resolution functions. Also
this interface is satisfied by the cas.
=> pkg: add an acirenderer library.

pkg/acirenderer/acirenderer.go, pkg/acirenderer/acirenderer_test.go, pkg/acirenderer/resolve.go, pkg/acirenderer/store_test.go, test
The last patch is the interesting one (the first one is from #216).
This patch generates the dependencies list given an ImageID or an App name and
labels.
=> acirenderer: add dependencies resolving

SPEC.md, ace/validator.go, examples/container.json, schema/container.go
When the ACE has need for amending the app defaults in any way, it
duplicates the original app object from the image manifest into the
appOverride making amendments to the CRM copy.
=> schema: introduce appOverride to the CRM RuntimeApp

Godeps/Godeps.json, Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource/quantity.go, Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource/quantity_example_test.go, Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource/quantity_test.go, Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource/suffix.go, Godeps/_workspace/src/github.com/spf13/pflag/LICENSE, Godeps/_workspace/src/github.com/spf13/pflag/README.md, Godeps/_workspace/src/github.com/spf13/pflag/example_test.go, Godeps/_workspace/src/github.com/spf13/pflag/export_test.go, Godeps/_workspace/src/github.com/spf13/pflag/flag.go, Godeps/_workspace/src/github.com/spf13/pflag/flag_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/LICENSE, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/benchmark_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/dec.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/dec_go1_2_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/dec_internal_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/dec_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/example_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/rounder.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/rounder_example_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/rounder_test.go, SPEC.md, examples/container.json, examples/image.json, schema/types/isolator.go, schema/types/isolator_linux_specific.go, schema/types/isolator_resources.go, schema/types/isolator_test.go
Until now isolators have not had a schema and had to be serialized to a
string. Fix this by making an isolator an object with only a single
required field: "name". Everything else goes into isolator specific
fields.
Credits and influences:
http://www.freedesktop.org/software/systemd/man/systemd.exec.html#CapabilityBoundingSet=
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/resources.md
https://github.com/google/lmctfy/blob/master/include/lmctfy.proto
https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt
https://www.kernel.org/doc/Documentation/cgroups/net_cls.txt
https://www.kernel.org/doc/Documentation/cgroups/blkio-controller.txt
=> SPEC: make isolators objects instead of strings

schema/types/isolator_resources.go
This was just a stupid oversight in implementing these types. Correct it
so a user has access to the names if needed.
=> schema: add resource type name constants

SPEC.md
- Executors MUST act on limits, instead of MAY.
- Move to one-sentence-per-line and add some keyword highlighting
=> SPEC: tweak resource isolator wording

SPEC.md, ace/validator.go
It is useful for executor implementations to provide various environment 
variables to applications, so the specification should only mandate certain
values rather than the complete set.
=> SPEC: specify only minimum set of environment vars

SPEC.md, schema/types/isolator.go, schema/types/isolator_linux_specific.go, schema/types/isolator_resources.go, schema/types/isolator_test.go
Also reworks isolators to assertValid during unmarshalling
and be tollerant of unrecognized isolators. Added Unrecognized()
method to return unrecognized isolotars for warnings.
=> spec: isolator is name/value pair; name is of ACName type

schema/types/isolator.go
Build a valid v0.4.0 image manifest with the following isolator using actool v0.4.0:
```
{
"name": "os/linux/capabilities-retain-set",
"value": {
"set": ["CAP_NET_ADMIN"]
}
}
```
You will get the following error message:
```
build: Unable to close image workspace/aci/kube-proxy.aci: json: error calling MarshalJSON for type *types.App: json: error calling MarshalJSON for type json.RawMessage: unexpected end of JSON input
```
=> schema: marshalling of isolators does not work

aci/build.go
actool will hang if fifos are opened during build.  sockets probably shouldn't be opened either.
=> actool: don't try to open named pipes or sockets

OS-SPEC.md
/dev/shm is expected by applications using glibc:
https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt
/dev/shm is mounted as tmpfs by
- Docker
https://github.com/docker/libcontainer/blob/master/SPEC.md#filesystem
- systemd-nspawn
http://cgit.freedesktop.org/systemd/systemd/tree/src/nspawn/nspawn.c#n862
=> OS-SPEC.md: add /dev/shm

schema/types/volume.go, schema/types/volume_test.go
Fix https://github.com/coreos/rocket/issues/615
By default the `readOnly` field in Volume is `false`, this will cause
an app container runtime to always override the image manifest's volume
mounts setting. Change it to `*bool` gives us the ability to ignore this
field in the container runtime manifest.
=> schema: replace bool with *bool in types.Volume.

SPEC.md, schema/pod.go, schema/pod_test.go
Since 9aafd97 landed, app references within a pod gained a name field that is
distinct from the name of the underlying image. However, the spec did not
address whether this field needed to be unique, which made it unclear as to
how to facilitate e.g. multiple apps within a pod using the same image.
This makes the name field a) required, and b) unique within a pod.
Accordingly, apps in a running pod can now be uniquely, globally identified by
the combination of Pod UUID + name.
Fixes #84
=> spec: enforce unique app names within a pod

OS-SPEC.md
Interactive containers expect /dev/pts.
Also, /dev/ptmx needs to be redirected to /dev/pts/ptmx using a symlink
or a bind-mount. See
https://www.kernel.org/doc/Documentation/filesystems/devpts.txt
=> OS-SPEC.md: add /dev/pts and /dev/ptmx

schema/pod.go
The arrival of pods in #207 removed the UUID field from the PodManifest
(instead requiring that the metadata service expose it), but this was sadly
not reflected in the actual schema code.
/cc @eyakubovich @philips @cdaylward
=> schema/pod: remove UUID field

discovery/discovery_test.go, discovery/parse.go, discovery/parse_test.go, schema/types/labels.go
The first patch changes the discovery.App labels name from a string to a types.ACNAme to be consistent with types.Label.
The second patch will add an utility method to convert the labels map in discovery.App to a types.Labels slice.
This is useful for future rocket patches to avoid adding additional converting code to it.
=> Use types.ACName in parse.App labels name and add a LabelsFromMap function.

schema/types/acname.go, schema/types/acname_test.go
This function panics when the given string is not a valid ACName. It's
useful for cases where we're sure the ACName we pass is valid.
=> types/acname: add MustACName function

pkg/acirenderer/acirenderer.go
The current implementation of PathWhitelist is slow when the list of
files is big.
This commit sets the current PathWhitelist outside of the Walk loop to
avoid calling pwlToMap on every file. It also removes a
filepath.Clean() call since the following filepath.Join will call Clean
anyway.
This helps with appc/docker2aci#34
=> acirenderer: optimize PathWhitelist handling

actool/actool.go, actool/manifest.go, actool/validate.go, schema/types/mountpoint.go, schema/types/mountpoint_test.go
The manifest can be printed as is: 
```
$ actool cat-manifest file.aci
```
Or it can be parsed and printed in a pretty form:
```
$ actool cat-manifest --pretty-print file.aci
```
The ACI can be copied with an alternative manifest:
```
$ actool patch-manifest --manifest=./manifest file.aci target.aci
$ mv target.aci file.aci
```
Or this can be done in one operation with --replace:
```
$ actool patch-manifest --manifest=./manifest --replace file.aci
```
The manifest could be patched without providing the whole manifest file:
```
$ actool patch-manifest --name=example.com/app \
--capability=CAP_NET_ADMIN,CAP_SYS_ADMIN \
--replace \
file.aci
```
=> actool: new subcommands: cat-manifest and patch-manifest

discovery/parse.go, discovery/parse_test.go, schema/types/labels.go
As discussed in https://github.com/coreos/rkt/pull/661/files#r27144083 this PR adds two new methods useful for future work on rkt for easily converting between manifest data and discovery.App.
=> Add App.String() and Labels.ToMap methods.

SPEC.md
Replace TODOs in spec text with GitHub issues:
- https://github.com/appc/spec/issues/276
- https://github.com/appc/spec/issues/277
- https://github.com/appc/spec/issues/278
Change block isolator wording to apply to specific devices (looks like 
previous situation was copypastaed from network isolators)
=> spec: remove TODOs, fix block isolators

SPEC.md
- codify/define "discovery URL" + template
- remove misleading `?torrent` tag
- remove ACE references, instead talk about discovery clients
- discuss behaviour in case of multiple `ac-discovery` tags
=> SPEC: discovery clarifications

schema/types/labels.go, schema/types/labels_test.go
Following on from discussions in #284 and #287, this adds the `aarch64`
architecture as a valid value for the architecture label when `os` is set to
`linux`.
=> schema: add linux/aarch64 as valid os/arch

MAINTAINERS, POLICY.md
Per discussion on the appc-dev mailing list [1], and according to the current
governance policy, Tim has been sucessfully nominated as a new maintainer of
the appc spec.
Also updates POLICY.md to reflect that CoreOS is no longer a majority of 
maintainers, and fix a typo (s/Blaze/Bazel/).
[1] https://groups.google.com/d/msg/appc-dev/F1vAVfIyoys/m09GFzE8oxQJ
=> *: add Tim Hockin (thockin) to MAINTAINERS

SPEC.md
Fixing a small typo in the example spec.
=> typo: "resources/cpu" -> "resource/cpu"

schema/types/labels.go, schema/types/labels_test.go
After consulting with ARM engineers, it seems the most sensible approach to
architectures pre-aarch64 is to support the two endian variants of ARMv7:
`armv7l` for little-endian and `armv7b` for big-endian.
These also correspond to the output of `uname -m` on Linux systems.
This avoids the somewhat arbitrary armel/armhf/armv7 distinctions
(partly by not accounting for architectures older than ARMv7).
Following up from #287, fixes #284
=> schema: add armv7l/armv7b as valid archs for linux

SPEC.md
Though I like the grouping of types in #314, this will start the definition around valid `acKind` values.
=> SPEC.md: section on acKind field

SPEC.md
One of the parameters under both "resource/block-bandwidth" and "resource/block-iops" is "devicePaths", however it is not present in the examples, and instead the parameter "default" is present. Perhaps "default" should be replaced with "devicePaths"?
=> spec: devicePaths parameter missing from examples

SPEC.md
Make spec more vague around the issue of POD UUIDs.  This
allows for generation of UUIDs to occur on the metadata
service itself if desired by the implementation.
Fixes #324
=> SPEC: Make UUID generation more vague.

SPEC.md
As reported in #292, the example gpg command was truncating output by re-using
the input file. Instead, we write to a separate temporary output file and then
overwrite (mv) the original.
This also clarifies the ordering of operations for images: signing should
happen *after* (optional) encryption, not just compression. This was
previously discussed in #19, #156, and #204.
=> spec: fix gpg example and clarify ACI signing

pkg/device/device.go, pkg/device/device_posix.go, pkg/tarheader/pop_linux.go, pkg/tarheader/pop_posix.go, pkg/tarheader/pop_posix_test.go
Move them from tarheader to device package and export go functions. This
allows the use of these functions by other packages.
Add makedev function.
This will be used by the CopyTree function I talk about in [coreos/rkt#693 (comment)](https://github.com/coreos/rkt/issues/693#issuecomment-95625786).
=> pkg: export Makedev helpers

SPEC.md
Using container's IP for identify is problematic because:
1. It places a burden on the network impl to protect against IP spoofing
2. It prohibits the container from sharing the network with the host.
3. It makes it impossible to have a central metadata service if the
nodes are behind a NAT.
The use of bearer removes these constraints.
The token is passed in via AC_METADATA_TOKEN env var.
Fixes #153
=> spec: use bearer token for metadata service auth

SPEC.md
Some markdown parsers need a space before a list of bullets.
And the code type declarations on blocks can be pretty.
=> SPEC.md: formatting of bullets and blocks

README.md
Added Kurma to the list of implementations in the README. Looked like the list
was in alphabetical order.
@jonboulle @vbatts
=> README: Add Kurma to list of implementations

SPEC.md
"Writing files leads to assumptions like a libc environment attempting parse /etc/hosts"
I don't buy that this is a problem.  If you want to change something so fundamental to the UNIX way of operating, you can't just plonk it on people's heads and demand they change.  I find this to be a weak argument.  The rest seem OK, though.
=> Metadata: specious argument

SPEC.md
Maybe worth clarifying that auth tokens must not be easily discoverable (e.g. don't just use the pod UUID).  Containers will eventually attack hosts or other containers.  This should be tight enough to at least say that containers should have a VERY hard time guessing each others tokens.
=> Metadata clarification - tokens

SPEC.md
"if it meets one of three criteria" - then you define only two criteria.
=> Dependency matching: claims 3 criteria, lists 2

SPEC.md
Pod schema says "value can be a freeform string"
Image schema says just list of objects and nothing more
Isolators section says value "can be an arbitrary JSON value"
=> Spec unclear on isolators

SPEC.md
'the following represent roughly the same value: 128974848, "129e6", "129M" , "123Mi"'
To my eyes these are NOT the same at all, and comparing them makes me nervous.  129e6 and 129M are exactly 129000000.  123Mi is exactly 128974848.  This is VERY IMPORTANT.  Please clarify the intentions here.
For example, kubernetes is very strict that the resource encoding is exact and not lossy at all, except in one way (that we only handle 3 decimal places).  We spec that numbers are *never* actually stored as floating point values (it's lossy).  It's easy to screw this up in subtle ways that make the whole thing become trouble.  E.g. you can easily find a set of numbers which, after processing, add up to a feasible set in one order and not in another order.
=> Isolators suffixes

SPEC.md
- remove mount namespace requirement and instead switch to "shared
volumes" language. As raised previously elsewhere [1][1] [2][2], this
is somewhat moot since applications start chrooted into their
respective filesystems anyway.
- Add illustrative explanation of the significance of the namespaces
[1]:
https://github.com/GoogleCloudPlatform/kubernetes/pull/4701#discussion_r25125656
[2]: https://github.com/appc/spec/issues/318
Fixes #318
=> spec: tweak pod definition

OS-SPEC.md, SPEC.md
As of c8559a283567c1c6840258c6833f5f832fc66cb6 the environment variables mandated by the spec are [as follows]([https://github.com/appc/spec/blob/c8559a283567c1c6840258c6833f5f832fc66cb6/SPEC.md#execution-environment]):
1. `PATH`
2. `USER`
3. `LOGNAME` (same as `USER`)
4. `HOME`
5. `SHELL`
6. `AC_APP_NAME`
7. `AC_METADATA_URL` 
1, 2 and 3 seem relatively uncontroversial - it's reasonable to assume every app executing on a modern OS has these concepts (inherently associated with the process). 6 and 7 are similarly straightforward expectations defined clearly in the spec itself. 
4 and 5 are slightly more problematic because, although part of the POSIX `passwd`, their significance and relevance for applications executing in containers is murky. They are conceptually really associated with …
=> spec: reconsider SHELL/HOME environment variables

SPEC.md, examples/image.json, schema/types/isolator_linux_specific.go, schema/types/isolator_test.go
This essentially offers two options:
- Remove certain capabilities and include all others
- Retain certain capabilities and removea all others
Fix everything up to be consistent with the remove-set and retain-set
language.
=> SPEC: clarify language around the capabilities flags

SPEC.md
The requirement has no clear purpose, and makes it harder to use some
tools. In particular, FreeBSD base system includes `/usr/bin/fetch`
that could be used to query the metadata service, but which doesn't
support setting custom headers. Removing this requirement makes it
possible to use FreeBSD base system without any additional software
installed.
An alternative approach, if there is any reason for keeping this requirement, would be to clearly specify the repercussions (and lower the requirement to SHOULD), e.g.:
> Clients querying any of these endpoints SHOULD specify the `Metadata-Flavor: AppContainer` header. ACE implementations MAY reject metadata service requests that do not contain such header, responding with a "400 Bad Request" HTTP status.
=> Delete the "Metadata-Flavor:" header requirement

SPEC.md
Make it clear in the spec that the encryption method is based on OpenPGP symmetric AES cipher with 256-bit key. Also add a short note about encryption after compression and a recommendation for implementations to allow disablement of compression.
=> Clarify encryption method and add a note about semantic security

SPEC.md
fixes #389
> CAP_SYS_ADMIN which is quite powerful and should probably be
> discouraged, ie. not given in the example.
=> spec: remove CAP_SYS_ADMIN from example manifest

discovery/discovery.go, discovery/parse.go, discovery/parse_test.go
The discovery.App struct is passed by value to the doDiscover function
but the App.Labels map references the same underlying data structures of
the passed App.Labels map. So adding the "version" label will changes
the passed App.Labels.
Fix this using a copy of discovery.App.
=> discovery: use a copy of app before adding defaultVersion label.

SPEC.md, examples/image.json, pkg/acirenderer/acirenderer.go, pkg/acirenderer/acirenderer_test.go, pkg/acirenderer/resolve.go, schema/types/dependencies.go, schema/types/dependencies_test.go
Use `app name` in this section seems a little bit out of tune to me. How about changing it to `image name`?
/cc @jonboulle @philips
=> spec: Rename app name to image name.

discovery/discovery_test.go, discovery/http.go, discovery/http_test.go
This changes the HTTP handling within the discovery package to make its
http.Client an exported field. This has a couple of use cases where consumers
of the package may want to customize the handling, such as:
* Adjusting the dial handler with custom timeouts
* Altering the http.Transport on the client for testing outside of the
discovery package.
* Altering the proxy used for discovery requests without setting altering the
proxy settings for the whole process.
This also updates the internal test handling to use an internal interface that
is used to wrap http.Client.Get(). With this, the way the existing tests were
mocking out requests is preserved.
=> discovery: Update the package to expose the http.Client

SPEC.md
In likeness to other existing container technologies, an enviroment
variable of `container` set to the name of the runtime tool. Prior tool
examples include "lxc", "systemd-nspawn", "lxc-libvirt".
May require a little conversation, but it is a change I think will be ultimately accommodating to folks developing to the the container space.
=> SPEC.md: "container" env variable

pkg/tarheader/pop_posix.go
FreeBSD's `st.Rdev` is `uint32`, adding explicit cast up to `uint64` to get signature working.
=> pkg/tarheader: Explicitly cast st.Rdev to uint64 to make it build on FreeBSD

schema/types/dependencies.go, spec/aci.md
Dependency references should have an optional "size" or "length" field to allow clients to prevent against DOS attacks  ([e.g.](https://github.com/theupdateframework/tuf/blob/d7fd61234e423a30b5ab10253f347fbd515180af/docs/tuf-spec.txt#L138)) when discovering and retrieiving them.
=> spec: dependencies should have "size"/"length"

ace/build_aci, build, test
Changed build and test scripts to work on FreeBSD. Removed harcoded setting GOOS/GOARCH to Linux/amd64; if cross-compilation is needed, will add an argument to set the target arch.
Are there any instructions on how to use the validator ACIs? A validator pod manifest, maybe?
=> Make build scripts work on FreeBSD

pkg/acirenderer/acirenderer.go, pkg/acirenderer/acirenderer_test.go
Related to https://github.com/coreos/rkt/issues/1034#issuecomment-111578112
=> pkg/acirenderer: fix renderer to render empty rootfs directory as well.

schema/types/labels.go, schema/types/labels_test.go
This PR brings support for a Raspberry Pi 1. In contrast a Raspberry 2 uses "armv7l" which is already supported in `spec`.
With some more detailed tests I had problems to import ARM Docker images with `docker2aci`. This was due to the fact that Docker uses only `"Os": "linux"` and "`Architecture": "arm"` (can be determined with `docker insect <imageid>`. These issues could be easily solved by adding "arm" as a valid arch.
Fixes #417
=> spec: Add schema 'armv6l' as valid arch for linux

ace/validator.go
=> ace/validator: update the expected app name to ACName compatible.

README.md
Fix link to the Image Layout section which is no longer valid after
commit 9f09e6de0d20 ("*: break spec into discrete sections").
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> README.md: Update link to Image Layout section after SPEC.md split

spec/pods.md
The spec for the "empty" volume kind is unclear. See https://github.com/appc/spec/issues/183 for the issue/discussion around this.
**Note:** My change proposes the rather strong spec of: `lifetime of the empty volume == lifetime of the pod` 
I feel that this makes the use case of "empty" more clear than specifying `lifetime of the empty volume >= lifetime of the pod` as was suggested in https://github.com/appc/spec/issues/183#issuecomment-98582304 However, I don't have a strong opinion around this, and would be happy to change what I wrote.
=> spec pods: Clarify empty volume kind

ace/build_aci
We were generating an .asc signature file but we didn't specify --armor
to the gpg commad so it was a binary file instead of an ASCII armored
file.
=> ace: generate an armored gpg signature

actool/manifest.go, examples/image.json, schema/types/isolator_test.go, spec/ace.md, spec/aci.md
This helps us to be consistent with Kubernetes's CPU resource unit.
=> spec: Use cpu-core unit in resource/cpu.

spec/aci.md, spec/discovery.md
Now aci.md "Dependency Matching" chapter explains how dependency's name and
labels are used for discovery and then compared to the name and labels in the
Image Manifest of the retrieved image.
This labels matching should be done for every discovery.
This patch moves the labels matching part to discovery, and keeps in "Dependency
Matching" the additional ImageID check.
From the logical point of view of "Dependency Matching" this means that now labels
matching is done before ImageID matching since it's included in the discovery
logic.
=> spec: move labels matching part to discovery.

ace/os_default.go, ace/os_freebsd.go, ace/os_linux.go, ace/os_shared.go, ace/validator.go, ace/validator_test.go
This includes:
- A proper check for Linux. The previous one was just checking if the
devices were the same, this is not true for bind-mounts within the
same device
- A check for FreeBSD courtesy of Maciej Pasternacki
<maciej@3ofcoins.net>. Jails seem to have f_fsid set to zero so the
original check didn't work. Now we check r_fstypename, f_mntfromname
and f_mntonname too.
- As a fallback (for other systems) we do the same as the original code:
just check the f_fsid.
Fixes #464 
cc @mpasternacki
=> ace/validator: fix mountpoint checks

ace/os_default.go, ace/os_freebsd.go, ace/os_linux.go
Noticed in #467. Also tweaked import style for consistency.
=> ace: add missing license header

aci/layout.go, aci/layout_test.go, actool/build.go, actool/validate.go, schema/types/semver.go
We print a warning if the ACVersion of our input manifest is older than
the current version. This encourages ACI builders to update their
manifests but still allows them to build ACIs with an old ACVersion.
=> actool: warn if manifest's ACVersion is too old

aci/file.go, actool/manifest.go, actool/validate.go
this depends on #461. The relevant patch is `aci: make XzReader implement io.ReadCloser`
this is needed as the XzReader, now calling an external process, needs to be
closed or the underlying process will continue to read from the passed file
descriptor, creating a race with subsequent methods calling another XzReader.
The Close method closes the output pipe, kills the process and then waits for
it to exit.
A possible fix after/substituting this will be to migrate to a pure go xz decompressor like the one proposed in #455
This is a part of the fix for coreos/rkt#1224 (missing the rkt part using the right functions)
=> aci: make XzReader implement io.ReadCloser

aci/file.go, actool/manifest.go, actool/validate.go
now NewCompressedReader returns an io.Reader but gzip.NewReader returns an
io.ReadCloser that was leaked.
This patch makes NewCompressedReader return an io.ReadCloser and wraps others
implementing only io.Reader making them an io.ReadCloser with a fake Close
method.
Consequently NewCompressedTarReader must implement a Close method needed to
close the underlying CompressedReader.
In the meantime duplicated code from actool/validate.go is removed in favor of
the one provided by the aci package.
In another patch also XzReader will be changed to become an io.ReadCloser.
As this is an api change, at least rkt and docker2aci needs to be patched when
updating vendored appc/spec in rkt.
=> aci: make NewCompressedReader an io.ReadCloser

schema/lastditch/doc.go, schema/lastditch/image.go, schema/lastditch/image_test.go, schema/lastditch/pod.go, schema/lastditch/pod_test.go, test
These do a really minimal validation (only whether the parsed bytes
are indeed JSON and acKind is alright) and get only a part of data
from manifest (names, mostly).
Useful for getting some information about badly-formed manifest for
better error messages.
=> schema: Add a last-ditch parser of pod and image manifests

schema/types/app.go, spec/aci.md
Image manifest allows me to spec what GID to run as, but does not allow me to add supplemental groups.  This is important for many reasons, not the least of which is disk quota management.
=> spec: support supplementary GIDs

ace/validator.go
When requesting the metadata service to verify a signature from another pod,
the uuid of the pod needs to be passed as an HTTP-POST option. According to
the spec, the name of the option is "uuid" and not "uid".
=> ace validator: fix typo in the HTTP-POST options sent to metadata srv

aci/build.go, actool/build.go
This callback allows users to modify the final tar headers or filter out
tar entries when building an ACI.
Also, add a --owner-root flag to acbuild so users can adjust the uids
and gids of all the files and directories in stage1 to 0:0. This is
needed by rkt: https://github.com/coreos/rkt/issues/1453
Fixes #498
=> aci build: add a callback to BuildWalker

schema/lastditch/common_test.go, schema/lastditch/image.go, schema/lastditch/image_test.go, schema/lastditch/labels.go, schema/lastditch/pod.go, schema/lastditch/pod_test.go
This PR does some cleanups first and then adds labels to pod's runtime image and to image manifest.
This may be useful for rkt to extract the version of an image (and maybe arch and os if there is need) in error cases.
=> last-ditch: Handle labels

discovery/discovery.go, discovery/parse.go, discovery/parse_test.go
Appc label values can be arbitrary strings, so they might need to be
escaped to become a valid URL label.
The problem arose when the "version" label has a value like
"0.8.1+git734734", where the "+" is a reserved char as noted in RFC
3986, section 2.2.
=> discovery: URL-encode label values

spec/ace.md
Metadata service requires running a daemon which might
be burdensome for some implementations and use cases.
=> spec: relax the requirement of metadata service

Godeps/Godeps.json, Godeps/_workspace/src/github.com/camlistore/camlistore/pkg/errorutil/highlight.go, schema/image.go, schema/pod.go
With line and column numbers, and a highlight string.
Example:
```
Error at line 13, column 8
12:       }
13:       {
^
invalid character '{' after array element
```
=> schema: add better manifest parsing errors

actool/discover.go, discovery/discovery.go, discovery/discovery_test.go, discovery/http.go, discovery/http_test.go
The discovery library doesn't have support for passing auth credentials so it will fail in servers that have authentication enabled.
This PR modifies the discovery functions to accept a map with per-host headers. If the host in the discovery URL is specified in this parameter, the corresponding headers will be applied when doing the discovery.
As an alternative, we could change the parameter to be just a header and leave converting the app to a hostname and selecting the right header to the library caller.
This is not ready for review/merge, I just want to get some feedback on the general idea.
Related: https://github.com/coreos/rkt/issues/1516
=> discovery: add per-host HTTP headers to discovery functions

examples/pod_runtime.json, schema/types/volume.go, schema/types/volume_test.go, spec/pods.md
This allows setting which UID and GID and permission mode will be
applied to an empty volume.
We only allow UIDs and GIDs because a user/group name wouldn't make
sense in the Pod context: each app in the Pod can have a different
/etc/passwd with different mappings.
Fixes #526
=> schema/types: add mode, uid and gid for empty volumes

discovery/parse.go, schema/common/common.go, schema/common/common_test.go, schema/types/mountpoint.go, schema/types/port.go, schema/types/volume.go
To allow values with URL special characters like "+" or "&".
Fixes #465 
cc @krnowak
=> schema/types: escape values when parsing

spec/OS-SPEC.md
Partially addresses concerns raised in #144
=> os-spec: ACE SHOULD provide /etc/hosts on Linux

schema/types/volume.go, schema/types/volume_test.go
tl;dr: this patch:
- fixes a panic in the Volume type's String() method
- ensures that the serialization of a Volume to/from a string is
reversible - i.e., `s == VolumeFromString(s).String()`
Full details:
The `Volume` type is polymorphic; it can be of several different Kinds,
and for each Kind only a select few fields are valid. When new fields
(`mode`, `uid`, `gid`) were added to the `empty` volume Kind (via
26af7cefe402259b348fdfa2299d8d2e0a595e2e), they were simply added as new
fields. However, this means that Volume structs of Kinds for which those
fields are not valid (e.g. the `host` Kind) would necessarily have
values set in those fields - since in Go any fields will be
automatically set to their zero value. To mitigate this, the previous
code set special sentinel values to those …
=> schema/types: rework empty volume type code

schema/types/isolator_linux_specific.go
appc/spec v0.7.2 broke "actool patch-manifest --capability" during the
isolator refactoring https://github.com/appc/spec/pull/517.
Fixes https://github.com/appc/spec/issues/542
=> schema/types: fix capabilities marshaling

actool/discover.go, discovery/discovery.go, discovery/discovery_test.go, discovery/http.go, discovery/http_test.go
The "insecure" was previously used to allow http. This is now split into
two flags "insecureHttp" and "insecureTls".
Related to https://github.com/appc/spec/issues/545
-----
/cc @krnowak 
I will need this for tests in rkt, see https://github.com/coreos/rkt/pull/1822.
=> discovery: add insecureTls flag to skip TLS checks

GUIDE.md, spec/discovery.md
The value of Simple Discovery has always been somewhat dubious, and most
implementations of the spec (`apcera/kurma`, `3ofcoins/jetpack`,
`coreos/rkt`) never actually implemented it. On the other hand, meta
discovery is used actively and arguably is synonymous with discovery.
This PR proposes removing the concept of Simple Discovery entirely and
making that synonymousness official - i.e., App Container Image
Discovery is what was formerly called Meta Discovery.
References:
https://github.com/appc/spec/issues/56
https://github.com/appc/spec/issues/140
https://github.com/appc/spec/pull/118
https://github.com/coreos/rkt/pull/383
/cc @philips @krobertson
=> spec/discovery: remove Simple Discovery entirely

spec/aci.md
In the security note located in "Image Archives" section of App Container Image spec there was a typo mentioning compression when it should say encryption.
=> Fix typo in security note of ACI spec

ace/build_aci, ace/image_manifest_main.json.in, ace/image_manifest_sidekick.json.in
Currently, `os` of built validator ACI is hardcoded to `linux`, which makes ugly patches necessary to make it run properly on Jetpack. This patch makes the build script use current `GOOS` and `GOARCH` values for the `os` and `arch` tags.
=> ace: use actual GOOS and GOARCH when building validator ACIs

pkg/device/device_linux.go
On linux platform - remove dependency on macros from glibc headers.
With this change - whole library can be used witouth CGO, so it can be
used to build fully statically linked binary.
=> Remove dependency on glibc in linux systems.

spec/pods.md
This corrects the pod spec to clarify that the 'mode' field under
volumes is a string and not an integer. Filing to quote the value will
break unmarshalling a manifest.
@jonboulle
=> spec: Fix pod spec to clarify the 'mode' field is a string

spec/ace.md, spec/aci.md
Fixes https://github.com/appc/spec/issues/538
-----
The ordering explained in this PR is the ordering currently implemented. But the chain of `pathWhitelist` seems to be only partially implemented in [GetRenderedACIFromList()](https://github.com/appc/spec/blob/master/pkg/acirenderer/acirenderer.go#L100).
/cc @n0rad
=> spec: clarify image dependencies

spec/ace.md
Added a short note that dependencies can form a tree or a directed
acyclic graph as well if they share a common dependency.
FYI PR @jonboulle @krnowak @alban 
Following up on https://github.com/appc/spec/pull/555#issuecomment-201100795
=> spec: Added note that dependencies can form a directed acyclic graph

Godeps/Godeps.json, Godeps/_workspace/src/golang.org/x/net/html/charset/charset.go, Godeps/_workspace/src/golang.org/x/net/html/example_test.go, Godeps/_workspace/src/golang.org/x/net/html/node.go, Godeps/_workspace/src/golang.org/x/net/html/parse.go, Godeps/_workspace/src/golang.org/x/net/html/parse_test.go, Godeps/_workspace/src/golang.org/x/net/html/token.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/resource/quantity.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/resource/quantity_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/dec_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/example_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/rounder_example_test.go, Godeps/_workspace/src/speter.net/go/exp/math/dec/inf/rounder_test.go, build, discovery/discovery.go, schema/image.go, schema/pod.go, schema/types/isolator_resources.go, schema/types/isolator_resources_test.go, schema/types/semver.go, schema/types/semver_test.go
Rewritten imports can make it difficult to vendor the code in other
packages. The only downside to un-rewriting (AFAICT) is that `actool` is
no longer `go get`able, but this is not something we endorsed in the
first place.
=> Godeps: unrewrite import paths

examples/image.json, spec/ace.md
Fixes https://github.com/appc/spec/issues/598
-----
/cc @iaguis @jonboulle
=> spec/ace.md: define the default capability set

schema/pod.go, spec/ace.md, spec/pods.md
Adds `readOnlyRootFS` field for mounting rootfs of an app as read-only.
Fixes #245 
cc @jonboulle
=> spec/ace: add optional read-only rootfs field

ace/validator.go
- remove extra trailing slash from URL
- unmarshal JSON to pointers
- use req.URL for feedback (req.RequestURI was empty)
=> ace/validator.go: small fixes

actool/manifest.go, examples/image.json, schema/types/isolator_linux_specific.go, schema/types/isolator_test.go, spec/ace.md
This adds a new no-new-privs isolator type.
actool support was added for patching a manifest:
`actool patch-manifest -isolators='os/linux/no-new-privs,true'`.
This is a prerequisite for https://github.com/coreos/rkt/issues/1469.
=> spec: implement os/linux/no-new-privs isolator

actool/manifest.go, examples/image.json, schema/types/app.go, schema/types/isolator.go, schema/types/isolator_linux_specific.go, schema/types/isolator_linux_specific_test.go, schema/types/isolator_resources.go, spec/ace.md
This is a proposal for two Linux-specific security isolators based on [seccomp filters](https://www.kernel.org/doc/Documentation/prctl/seccomp_filter.txt). It follows closely the capabilities isolators, where two modes are provided: "remove-set" (blacklisting) and "retain-set" (whitelisting).
Given the huge number of syscalls that can be specified this way and the on-going discussion about sensible defaults, this specification doesn't hardcode any list but let implementations some freedom to provide groups/wildcards via `@`-prefixed special values. Users can decide to provide their own custom filters, or just opt-in/opt-out those implementations-provided filters.
Fixes #529
=> ace: add Linux-specific seccomp isolator

actool/discover.go, discovery/discovery.go, discovery/discovery_test.go, discovery/http.go, discovery/http_test.go
Currently the ACI spec only supports discovery on ports 443 and 80, this
does not allow using a discovery server on any other ports.
This commit adds an argument allowing for discovery on arbitrary ports.
If the argument is not specified (as in, is 0), the default ports are
used.
Replaces https://github.com/appc/spec/pull/110#issuecomment-227428866.
Prompted by https://github.com/appc/acpush/issues/6.
=> discovery: add port parameters

build
Go 1.5 needs the environment flag `GO15VENDOREXPERIMENT=1` set to detect the deps in the _vendor/_ directory. Ideally it would be done dynamically, but could just be added to the scripts statically too.
/cc @jonboulle
=> build/test: fail on Go1 .5

schema/types/isolator.go
Even though Isolator instances should be constructed via
unmarshaling, library users may still construct one directly
with a nil value.
This commit fixes the validator to handle this error gracefully
instead of panicing.
=> schema/types: don't panic validating incomplete isolators

schema/types/volume.go, schema/types/volume_test.go, spec/pods.md
Closes #622.
It is still "WIP" for now because I would like to test it first.
/cc @steveeJ @jonboulle
=> types/volume: add recursive flag

actool/manifest.go
This commit unifies patch-manifest behavior so that --capability
and --revoke-capability are able to override existing isolators.
It will also remove one possible way of generating invalid
manifests with multiple conflicting capabilitiess isolators.
=> actool: allow patch-manifest to override caps isolators

examples/image.json, schema/types/annotations_test.go, spec/aci.md
supportNotify exposes if or not an application supports notifications
using sd_notify(). This information may be used to signal the init
process when a service is ready.
=> schema/app: add parameter to set support of sd_notify()

schema/types/labels.go, schema/types/labels_test.go
This adds labeling for the two endian variants of ppc64:
`ppc64le` for little-endian and `ppc64` for big-endian.
These explicitly correspond to `uname -m` on Linux systems.
=> schema: add ppc64le/ppc64 as valid linux archs

README.md
The "ACI" acronym starts to be relevant since the very beginning, but it's not defined anywhere in the starting page. I think it's important to have its expansion early to improve clarity.
=> Expand ACI acronym so that it's clear

discovery/http.go
This commit increases default connection timeout from 5s to 20s,
in order to gracefully accomodate for retrials. This will help in
overcoming soft-failure cases, like skipping a single faulty
resolvers in resolv.conf.
This is still a quite aggressive timeout, well below the Linux
timeout of 127s for new TCP connections.
=> discovery: increase default connection timeout

ace/validator.go
The runtimeApp annotations were merged over themself and not over the image
manifest annotations.
=> ace validator: fix app annotations validation.

schema/types/labels.go, schema/types/labels_test.go
This adds a new `s390x` architecture label for linux.
It maps to IBM z/Architecture: https://en.wikipedia.org/wiki/Z/Architecture
`s390x` is a 64-bits, aligned access, big-endian architecture:
https://wiki.debian.org/ArchitectureSpecificsMemo
This new label corresponds to `uname -m` on Linux systems, to GOARCH and
to the usual distro naming.
The usual GNU triplet for this is `s390x-ibm-linux-gnu`.
=> schema: add s390x as a valid linux architecture

examples/pod_runtime.json, schema/types/isolator_test.go, schema/types/isolator_unix.go, schema/types/isolator_unix_test.go, spec/ace.md
This PR introduces an "os/unix/sysctl" isolator, which applies at pod-level.
Closes #645
---
Arbitrary/controversial choices made here:
* isolator type, as it applies inside pod-context (like other isolators) instead of the host (like top-level stanzas: volumes, ports)
* ~~new "environment" isolator category, as it can also accommodate "ulimit" ones~~
=> spec: add os/unix/sysctl isolator

scripts/build-ace-validator-acis, scripts/build-release
- Move ace/build_aci to more appropriate location and name
and remove legacy hash/layout information
- Update release script with debugging information and invoking
ACE build, to make it less likely to forgot to release these too
in future
/cc @lucab
=> scripts: consolidate and tweak build/release

schema/pod.go, schema/types/app.go, schema/types/app_test.go, schema/types/cri_annotations.go, schema/types/cri_labels.go, schema/types/cri_labels_test.go, schema/types/mountpoint.go, schema/types/port.go
@yifan-gu @lucab @s-urbaniak I also updated the appc spec for annotations, along with port forwards. Take a look and we can update glide to pull from appc/spec's CRI branch.
=> Update appc data structures for CRI

actool/manifest.go, schema/types/isolator_linux_specific.go, schema/types/isolator_test.go
This is for coreos/rkt#3203
@lucab please review?
=> CRI: add oom_score_adj isolator

schema/types/labels.go, schema/types/labels_test.go
This commit introduces two helper functions to translate between
appc and golang os/architecture labels.
Closes https://github.com/appc/spec/issues/665
=> schema/types: translate between appc<->go arch tuples

schema/types/isolator_linux_specific.go, schema/types/isolator_linux_specific_test.go, schema/types/isolator_test.go, spec/ace.md
This commit introduces an "os/linux/selinux-context" isolator, which
can be applied at both app and pod scope.
=> spec: add os/linux/selinux-context isolator

ace/validator.go
These environment variables are no longer mandated by the spec per
appc/spec#273. It makes sense to remove them from the validator.
=> ace validator: Remove extra environment variables

spec/ace.md
The metadata service endpoints for creating and verifying an HMAC
signature already specify use of the POST method in their
descriptions. The other metadata service endpoints make no mention of
which HTTP methods are valid for them.
The current `rkt` implementation uses POST for the HMAC-related
endpoints and GET for all the others. This makes such behaviour
explicit in the spec.
=> spec/ace: Add HTTP methods for metadata service

spec/ace.md
Some of the metadata service endpoints explicitly specify a
Content-Type of `text/plain; charset=us-ascii`. For most other
endpoints, the ACE validator expects a Content-Type of
`application/json`.
The one exception is the HMAC verify endpoint which makes no mention
of its Content-Type nor even the contents of its response body. The
current implementation in `rkt` sets the Content-Type to
`text/plain; charset=us-ascii` which is now reflected in the spec.
=> spec/ace: Specify Content-Type for metadata service.

spec/discovery.md
=> fix(#680): spec/discovery.md: URL substitution example is wrong

schema/pod.go, schema/pod_test.go, spec/aci.md
Noteworthy: validation check now rejects manifest with duplicate volume names.
This PR adds a validation check on the `volumes` array to ensure that it doesn't contain any duplicate-named volumes (and corresponding tests). Also, it clarifies string-typing of annotations.
=> pod: now reject duplicate volume names in manifest

schema/types/labels.go, schema/types/labels_test.go
Prior to this change, the slice of labels produced by LabelsFromMap
could have any arbitrary ordering.
See https://github.com/appc/docker2aci/issues/245 for one of the issues
this causes in practice.
I also renamed the type 'labels' to 'labelsSlice' since, as it was, it
was being constantly shadowed.
This is not accompanied with any spec change since labels in the appc
spec are already a slice, and thus already have a consistent ordering.
It's unfortunate that a round trip of ToMap/FromMap won't be consistent,
but I don't think any callers actually do that currently.
=> schema/labels: consistently order LabelsFromMap

ace/image_manifest_main.json.in, ace/image_manifest_sidekick.json.in, scripts/build-ace-validator-acis
The manifest contains values for the ACI arch and OS, not the go
language values.  To avoid confusion, change the symbols 'GOOS" and
'GOARCH' to 'ACI_OS' and 'ACI_ARCH', and provide conversion as
needed.
Fixes errors like these when run an ARM64 machines:
bad arch "arm64" for linux (must be one of: [amd64 i386 aarch64 aarch64_be armv6l armv7l armv7b ppc64 ppc64le s390x])
=> ace: Fix manifest arch error

schema/types/isolator_linux_specific.go
errno symbols can contain numeric characters.
=> linuxSeccompBase: Fix errno check

schema/types/isolator_linux_specific.go, schema/types/isolator_linux_specific_test.go, schema/types/isolator_test.go, spec/ace.md
AppArmor is a very widely used isolator in the GNU/Linux community,
providing an "easier to configure" alternative to SELinux. From the
perspective of AppC this is a fairly simple addition (profile data is
not included in the spec and must already be loaded into the kernel).
This feature is required for feature parity for ACI containers with OCI
ones (as AppArmor is also supported as a first-class citizen in OCI).
/cc @flavio @vrothberg
Signed-off-by: Aleksa Sarai <asarai@suse.de>
=> spec: add os/linux/apparmor-profile isolator
