- SPEC.md
- ace/image_manifest_main.json
- ace/validator.go
- schema/types/app.go
- schema/types/app_test.go
TODO: need to add validator logic
> SPEC: add working directory

- ace/validator.go
- actool/actool.go
- actool/discover.go
- actool/help.go
> Switch remaining Fprintf(os.stderr) to stderr()

- ace/doc.go
- aci/doc.go
- actool/doc.go
- discovery/doc.go
- pkg/tarheader/doc.go
- schema/doc.go
- schema/types/doc.go
Who has two thumbs and doesn't know how to use godoc?
> *: fix godoc stanzas

- SPEC.md
These are some edits that resulted from notes I took while fully digesting the spec. The perspective is of a first-time reader, so I hope it's useful. I tried to group the edits into logical commits; feel free to discuss or reject any of them individually. Also, a few simple questions will follow...
> Relatively minor, clarifying edits

- schema/types/volume.go
> types/volume: verify that Source is absolute path

- SPEC.md
- examples/container.json
- schema/container.go
- schema/types/volume.go
- schema/types/volume_test.go
This is #143 with a little bit of cleanup.
> spec: add mountPoints and remove fulfills

- schema/types/volume.go
> schema/types: update volume docstrings

- SPEC.md
@cdaylward thoughts? I am not really sure about 4627 vs.
[RFC7159](https://tools.ietf.org/html/rfc7159)
> spec: be more specific about JSON

- SPEC.md
h/t to @cdaylward for pointing this out
Missed in https://github.com/appc/spec/pull/143/files
> spec: remove lingering "fulfills" reference

- README.md
> README: add some more FAQ type questions to the README

- README.md
This corrects a minor formatting error in the README.
> readme: correct Rocket link

- aci/file.go
> aci: use ManifestFile constant

- SPEC.md
Fixes #202
Short and sweet enough?
> spec: Add one-liner that apps in image dependencies are ignored.

- schema/types/ackind_test.go
- schema/types/acname.go
- schema/types/acname_test.go
- schema/types/annotations.go
- schema/types/annotations_test.go
- schema/types/app_test.go
Started hacking these up a while back but forgot to file a PR. 
There's no good reason for the schema to not have ~100% coverage, so this is
a small step towards that goal.
> schema/types: add tests for acname/ackind

- ace/image_manifest_main.json
Use the new isolator object type instead of the old one.
> ace: use new resource limit

- SPEC.md
- schema/container.go
- schema/types/port.go
Need a way to specify how the container ports will get mapped
to the host ports.
> Add ports section to CRM

- SPEC.md
Following some of the discussion in #207, this is an attempt to restructure
the spec by promoting the Pod to a top-level concept (along with ACIs, image
discovery, and ACE). Decoupling them from the executor section makes it
clearer that producing/manipulating pods can be completely independent of
execution.
> SPEC: promote Pods to top-level concept

- SPEC.md
> Add and remove empty lines as necessary

- schema/types/app.go
This allows applications to call app.Isolators.GetByName()
> types: fix isolators

- scripts/bump-release
> scripts: add bump-release script

- SPEC.md
> SPEC: fix typo

- CONTRIBUTING.md
- POLICY.md
- README.md
> *: add contribution and governance policy

- scripts/build-release
> scripts: add simple build-release script

- SPEC.md
The markdown on a couple of spots and implied $urltpml variable
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> SPEC.md: clearer meta discovery

- SPEC.md
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> SPEC.md: clearer variables in simple discovery

- SPEC.md
clear up wording on ac-discovery discovering from path.
> SPEC.md: meta-discovery wording

- SPEC.md
Per subject. These are very minor fixes.
> spec: two proofreading fixes

- SPEC.md
- schema/types/port.go
- schema/types/port_test.go
> spec: add port ranges

- SPEC.md
> SPEC.md: reference the spec version where mentioned

- SPEC.md
> SPEC: tweak metadata token wording

- SPEC.md
It says isolators "apply to all apps".  Does it mean they apply to each app or to the set of apps in total?  I assume in total, but it's not clear.
> Pod schema on isolators is unclear

- SPEC.md
'must be of the format "type-value", where "type" is "sha512"'
Does this mean that sha512 is the only supported type?  Earlier in the spec it read as if other common formats were valid, but not default.
> SPEC unclear: sha512 only supported form or just one of?

- README.md
Very minor change, just noticed on a readthrough.
> README.md: correctly show shell prompt.

- SPEC.md
Open question: do you really require routable IPs at this layer of the stack?  This implies that there is no way to do a machine-private container...
> Clarify net interfaces

- SPEC.md
It's not clear if I can say "/foo and everything under it" or not.
> pathWhitelist: can I make a recursive inclusion?

- pkg/acirenderer/acirenderer.go
- pkg/acirenderer/acirenderer_test.go
If an upper image overrides with another file type a directory in a
parent image, do not add the parent image directory's contents to the
rendered image.
For example, given an image A that depends on B:
B:
drwxr-xr-x ./
drwxr-xr-x ./rootfs
drwxr-xr-x ./rootfs/a
-rw-r--r-- ./rootfs/a/file01
drwxr-xr-x ./rootfs/a/b
-rw-r--r-- ./rootfs/a/b/file02
A:
drwxr-xr-x ./
drwxr-xr-x ./rootfs
-rw-r--r-- ./rootfs/a
The files from image B (`./rootfs/a/b`, `./rootfs/a/file01`,
`./rootfs/a/b/file02`) shouldn't be added to the rendered image.
> acirenderer: correctly handle overridden directories.

- SPEC.md
> SPEC.md: clarify timestamps

- SPEC.md
Reading the spec was a pretty good experience until I hit this paragraph, which took kind of a wild leap into future tense, passive voice, and a run-on sentence. FIFY :).
> spec.md: fixing some grammar/structure issues

- MAINTAINERS
Ken was successfully nominated as a new maintainer:
https://groups.google.com/d/msg/appc-dev/FMJBYH7zggY/GNhck9gG9G0J
> *: add Ken Robertson (@krobertson) to MAINTAINERS

- schema/types/labels.go
This function can be reused by rkt to check images against its own valid
OS and architectures.
Useful for coreos/rkt#271
> schema/types: export IsValidOSArch function

- actool/manifest.go
If a user sets patchExec and the original manifest is missing an App,
inject an empty App for them. However, if either patchUser or patchGroup
are set and there is still no App then bail out with the same error as
for other app-modifying parameters.
fixes #472
> actool: fix missing App panic in patchManifest

- schema/lastditch/doc.go
- schema/lastditch/image.go
- schema/lastditch/image_test.go
- schema/lastditch/pod.go
- schema/lastditch/pod_test.go
- test
This is just #476 + a small cleanup
> schema: add last-ditch parser

- pkg/device/device_posix.go
this makes this package buildable on osx.
> pkg/device: add darwin build flag

- README.md
Add oci2aci link at section #what-is-the-promise-of-the-app-container-spec
Signed-off-by: ChengTiesheng <chengtiesheng@huawei.com>
> Add oci2aci link

- SPEC.md
- spec/ace.md
Builds on #431 - in particular addressing the issues discussed @
https://github.com/appc/spec/pull/431#discussion_r32242878
https://github.com/appc/spec/pull/431#discussion_r32243094
> spec: app filesystem clarifications

- examples/pod_runtime.json
Following up from
https://github.com/appc/spec/pull/475#issuecomment-132827287
> examples: make volume/mount references consistent

- actool/manifest.go
Adds --supplementary-groups flag to actool which takes a comma-separated
list of gids.
> actool/manifest.go: support patching app.SupplementaryGroups

- GUIDE.md
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> GUIDE.md: Fix typo particulary => particularly

- schema/types/app.go
- schema/types/exec.go
> schema: fix field names in errors

- schema/types/isolator_resources.go
Fixes https://github.com/appc/spec/issues/552
> schema/types: add "AsIsolator" constructors

- ace/validator.go
- spec/ace.md
Addresses https://github.com/appc/spec/issues/373
> spec/ace.md: Add specificity to metadata endpoint descriptions.

- actool/discover.go
- discovery/discovery_test.go
- discovery/http.go
- discovery/http_test.go
See https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Following from conversation here: https://github.com/coreos/rkt/pull/1945#discussion_r49264529https://github.com/coreos/rkt/pull/1945#discussion_r49264529
> Make initialisms all caps

- actool/manifest.go
`actool patch-manifest` was able to add an isolator of type
`os/linux/capabilities-retain-set` with `--capability` but was not able to
add an isolator of type `os/linux/capabilities-remove-set`. This patch
adds this feature with `--revoke-capability`.
This will be useful for https://github.com/coreos/rkt/pull/2589
> actool: implement patch-manifest --revoke-capability

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go
- Godeps/_workspace/src/github.com/gogo/protobuf/proto/equal.go
- Godeps/_workspace/src/github.com/gogo/protobuf/proto/extensions.go
- Godeps/_workspace/src/github.com/gogo/protobuf/proto/lib.go
- Godeps/_workspace/src/github.com/gogo/protobuf/proto/properties.go
- Godeps/_workspace/src/github.com/gogo/protobuf/proto/text.go
- Godeps/_workspace/src/github.com/gogo/protobuf/proto/text_parser.go
Motivation is to vendor only tagged dependencies.
> deps:  gogo/protobuf: use v0.2

- schema/types/isolator_linux_specific.go
> CRI: add constructor for LinuxOOMScoreAdj

- schema/types/isolator_linux_specific.go
- schema/types/isolator_test.go
Partially fixes https://github.com/coreos/rkt/issues/3242
> CRI: add cpu-shares isolator
